### ISSUE TITLE
key requirement clarification

### ISSUE THREAD

**Issue by IronBit-0** [bodaay/GoOpenDrop#1]
In the readme it says:
> You must Do the extraction Step of Keys

Does this mean that you are required to extract your keys to send _any_ airdrop, or just airdrops to devices in "contact only" mode?

BTW this looks really cool! Thanks for uploading!

**Comment by bodaay** [comment]
I"m sorry I know I have to re-write README file

Keys required at the moment regardless of the receiver side Airdrop setting

I'm using the keys to initiate AWDL client/server

In opendrop, they had the option to use self-signed certificate. That option didn't work for me and I've decided not to implement it. 

I don't know the legal issues in sharing the keys, otherwise I would have included them within the repo.

**Comment by bodaay** [comment]
finally updated readme file with more detials, closing this issue
